app:
  name: "discord-bot"
  debug: ${APP_DEBUG}
  repository: "${APP_REPOSITORY}"
logger:
  level: "${LOG_LEVEL:debug}"
  disable: ${LOG_DISABLE:false}
discord:
  appID: "${DISCORD_APP_ID}"
  token: "${DISCORD_TOKEN}"
  intents:
    - Guilds
    - GuildVoiceStates
    - GuildMessageReactions
service:
  interactionCommand:
    ownerID: "${DISCORD_APP_OWNER_ID}"
